### PR TITLE
Add a cursor specific engine version

### PR DESCRIPTION
**Pull request by samdeanpinknews**
This should let the plugin install on cursor, versions 0.41.2 and above.

I've chosen that version because that's what I've got installed and have tested on.

### CODE REVIEW

**Comment by samdeanpinknews** [comment]
#12

**Comment by danvk** [comment]
Thanks. What's the effect of this? Will `vsce` check that the two versions are in agreement?

**Comment by samdeanpinknews** [comment]
Honestly, I have no idea.

I suspect that VS will ignore the cursor value as it doesn't know it exists, and Cursor will prefer the cursor value and use the vscode value as a fallback (which was where my error message was coming from)

As for vsce, I bet it won't do any sanity checks at all, as Cursor is a fork it has no responsibility over.

Which is an interesting question for you - do you want to be responsible for checking this works on multiple editors (I suspect not - and if not, feel free to decline this PR!)

**Comment by danvk** [comment]
I've never used Cursor (I hear good things, though!) so I think it would make the most sense to just keep the VS Code version pinned and let Cursor use that.

Did you try updating to 0.1.1, by the way? Does that fix #12?

**Comment by samdeanpinknews** [comment]
Hey, sorry, got stuck in work and then school run, sigh!

Looks like version 0.1.1 installs fine, so definitely no need for my changes :)

**Pull request closed without merging**
